### PR TITLE
Added workflow for when PRs are opened to develop

### PR DESCRIPTION
**Pull request by ericdrosas87**
EPO-6602

### CODE REVIEW

**Comment by ericdrosas87** [comment]
Hmm, the build didn't trigger for the open PR - will it happen after this PR is merged? I suppose so since the target branch is "develop" in the workflow YAML

**Comment by jtrouth** [comment]
@ericdrosas87 Do you want to preserve the `preview` branch name prefix to trigger as we did with the Obs site repos? If not then the `if` statement on the job needs to be updated.

**Comment by ericdrosas87** [comment]
@jtrouth Good catch, I'll remove that second condition and push out a new commit

**Comment by ericdrosas87** [comment]
Ah there goes the build - nice

**Comment by ericdrosas87** [comment]
This is good for review again @jtrouth , the build is now finishing successfully

**Review by jtrouth — APPROVED** [review]

**Pull request merged**
